from MLP import *
import load_mnist

EPOCAS = 2
TAXA_DE_APRENDIZAGEM = 3.0
MINI_LOTES = 10


CONJUNTO_TREINAMENTO, CONJUNTO_VALIDACAO, CONJUNTO_TESTE = load_mnist.load_data_wrapper()
CONJUNTO_TREINAMENTO = list(CONJUNTO_TREINAMENTO)


net = Network([784, 30, 10])
net.SGD(CONJUNTO_TREINAMENTO, EPOCAS, MINI_LOTES, TAXA_DE_APRENDIZAGEM, test_data=CONJUNTO_TESTE)